export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAILURE = "ORDER_CREATE_FAILURE";

export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_FAILURE = "USER_ORDERS_FAILURE";

export const USER_FILTER_ORDERS_REQUEST = "USER_FILTER_ORDERS_REQUEST";
export const USER_FILTER_ORDERS_SUCCESS = "USER_FILTER_ORDERS_SUCCESS";
export const USER_FILTER_ORDERS_FAILURE = "USER_FILTER_ORDERS_FAILURE";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAILURE = "ORDER_PAY_FAILURE";

export const ORDER_CHANGE_REQUEST = "ORDER_CHANGE_REQUEST";
export const ORDER_CHANGE_SUCCESS = "ORDER_CHANGE_SUCCESS";
export const ORDER_CHANGE_FAILURE = "ORDER_CHANGE_FAILURE";
