export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const PRODUCT_QUERY_REQUEST = "PRODUCT_QUERY_REQUEST";
export const PRODUCT_QUERY_SUCCESS = "PRODUCT_QUERY_SUCCESS";
export const PRODUCT_QUERY_FAILURE = "PRODUCT_QUERY_FAILURE";