export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILURE = "PRODUCT_LIST_FAILURE";

export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";

export const PRODUCT_QUERY_REQUEST = "PRODUCT_QUERY_REQUEST";
export const PRODUCT_QUERY_SUCCESS = "PRODUCT_QUERY_SUCCESS";
export const PRODUCT_QUERY_FAILURE = "PRODUCT_QUERY_FAILURE";

export const PRODUCT_PAGINATION_REQUEST = "PRODUCT_PAGINATION_REQUEST";
export const PRODUCT_PAGINATION_SUCCESS = "PRODUCT_PAGINATION_SUCCESS";
export const PRODUCT_PAGINATION_FAILURE = "PRODUCT_PAGINATION_FAILURE";
export const REMOVE_PAGINATION_PRODUCT = "REMOVE_PAGINATION_PRODUCT";

export const ADD_PRODUCT_REVIEW_REQUEST = "ADD_PRODUCT_REVIEW_REQUEST";
export const ADD_PRODUCT_REVIEW_SUCCESS = "ADD_PRODUCT_REVIEW_SUCCESS";
export const ADD_PRODUCT_REVIEW_FAILURE = "ADD_PRODUCT_REVIEW_FAILURE";
